services:
  # PostgreSQL Read (6432)
  postgres-read:
    image: postgres:17
    container_name: postgres-read-17
    environment:
      POSTGRES_DB: myapp_read
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "6432:5432"
    volumes:
      - ./postgres/data/read:/var/lib/postgresql/data
      - ./postgres/init/read:/docker-entrypoint-initdb.d
    restart: unless-stopped

  # PostgreSQL Write (7432)
  postgres-write:
    image: postgres:17
    container_name: postgres-write-17
    environment:
      POSTGRES_DB: myapp_write
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    ports:
      - "7432:5432"
    volumes:
      - ./postgres/data/write:/var/lib/postgresql/data
      - ./postgres/init/write:/docker-entrypoint-initdb.d
    restart: unless-stopped

  # DragonFly Shard 1
  dragonfly-1:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonfly-1
    ports:
      - "9379:6379"
    volumes:
      - ./dragonfly/data1:/data
    command: [ "--dir", "/data" ]
    restart: unless-stopped

  # DragonFly Shard 2
  dragonfly-2:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonfly-2
    ports:
      - "9380:6379"
    volumes:
      - ./dragonfly/data2:/data
    command: [ "--dir", "/data" ]
    restart: unless-stopped

  # DragonFly Shard 3
  dragonfly-3:
    image: docker.dragonflydb.io/dragonflydb/dragonfly
    container_name: dragonfly-3
    ports:
      - "9381:6379"
    volumes:
      - ./dragonfly/data3:/data
    command: [ "--dir", "/data" ]
    restart: unless-stopped


  # Redis
  redis:
    container_name: redis-local
    image: redis:7
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
    command: bash -c 'redis-server --requirepass KkWSa7RCJ0eK9SIAHzrQaw'

  # Redis Insight
  redis_insight:
    container_name: redis_insight-local
    image: redis/redisinsight:latest
    ports:
      - "5300:5540"
    volumes:
      - ./redis_insight_data:/db


  # Kafka with KRaft
  kafka:
    image: apache/kafka:3.7.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: "broker,controller"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      KAFKA_LISTENERS: "PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT"
      KAFKA_ADVERTISED_LISTENERS: "PLAINTEXT://localhost:9092"
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    volumes:
      - ./kafka/data:/tmp/kafka-logs
    restart: unless-stopped

  # HAProxy for Testing
  haproxy:
    image: haproxy:2.8
    container_name: haproxy-test
    ports:
      - "8888:8888"  # Stats page
      - "9080:8080"  # Load balancer port
    volumes:
      - ./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    restart: unless-stopped
    depends_on:
      - postgres-read
      - postgres-write